<a href="https://colab.research.google.com/github/abhishekmohanty297/Deep_Learning/blob/main/Basic_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREATING BASIC NEURAL NETWORK

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from google.colab import files
uploaded=files.upload()


Saving breast-cancer.csv to breast-cancer.csv


In [4]:
df=pd.read_csv('breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
df.shape

(569, 32)

In [6]:
df.drop(columns="id",inplace=True)

In [7]:
df.shape

(569, 31)

TRAIN TEST SPLIT

In [8]:
x=df.iloc[:,1:]
y=df.iloc[:,0]


In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

SCALING

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)

In [11]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [12]:
X_test

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [13]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

APPLY LABEL ENCODING

In [15]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(y_train)
Y_test=encoder.transform(y_test)

In [16]:
Y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [17]:
Y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

CONVERT NUMPY ARRAY TO PYTORCH TENSORS

In [18]:
import torch
x_train_tensor=torch.from_numpy(X_train).float()
x_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(Y_train).long()
y_test_tensor=torch.from_numpy(Y_test).long()

In [19]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]])

In [20]:
x_test_tensor

tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]])

DEFINING THE NEURAL NETWORK

In [21]:
class MysimpleNN():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward_pass(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss



In [22]:
learning_rate=0.1
epochs=25

In [23]:
# craete model
model=MysimpleNN(x_train_tensor)
model.weights

tensor([[0.4322],
        [0.1689],
        [0.7144],
        [0.0473],
        [0.9552],
        [0.8833],
        [0.9785],
        [0.2519],
        [0.0880],
        [0.9481],
        [0.7204],
        [0.3974],
        [0.0985],
        [0.0602],
        [0.4374],
        [0.9691],
        [0.7888],
        [0.6237],
        [0.5131],
        [0.5104],
        [0.5932],
        [0.9055],
        [0.2176],
        [0.1504],
        [0.2518],
        [0.3123],
        [0.1434],
        [0.8844],
        [0.7552],
        [0.8004]], dtype=torch.float64, requires_grad=True)

In [24]:
#Training the model
# step 1 : forward propagation
for epoch in range(epochs):
  y_pred=model.forward_pass(x_train_tensor.double())


  # step 2 : calculate the loss
  loss=model.loss_function(y_pred,y_train_tensor)

  # step 3 : backward propagation
  loss.backward()
  # parameters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-= learning_rate*model.bias.grad
  #Zero the gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch:{epoch+1},loss:{loss.item()}')

Epoch:1,loss:3.7941379844305514
Epoch:2,loss:3.668657482043175
Epoch:3,loss:3.5413726096171216
Epoch:4,loss:3.407844058290421
Epoch:5,loss:3.272053303900659
Epoch:6,loss:3.1290773322097394
Epoch:7,loss:2.984178966777418
Epoch:8,loss:2.8371322120364724
Epoch:9,loss:2.688690180446931
Epoch:10,loss:2.535346659151319
Epoch:11,loss:2.3835432831680543
Epoch:12,loss:2.2309850479435074
Epoch:13,loss:2.0786023934779485
Epoch:14,loss:1.9297057276122584
Epoch:15,loss:1.7877881119394379
Epoch:16,loss:1.649321777477335
Epoch:17,loss:1.5208983230325934
Epoch:18,loss:1.4024177491757828
Epoch:19,loss:1.2966168264470608
Epoch:20,loss:1.202635266928866
Epoch:21,loss:1.1221246347110245
Epoch:22,loss:1.0535614177661043
Epoch:23,loss:0.9954119227177847
Epoch:24,loss:0.9463042452157634
Epoch:25,loss:0.9049799280457347


In [25]:
model.weights

tensor([[ 0.1083],
        [-0.1595],
        [ 0.3543],
        [-0.2766],
        [ 0.4219],
        [ 0.1652],
        [ 0.3174],
        [-0.3683],
        [-0.3733],
        [ 0.4760],
        [ 0.3387],
        [ 0.1697],
        [-0.3066],
        [-0.2504],
        [ 0.1470],
        [ 0.3741],
        [ 0.3162],
        [ 0.0461],
        [ 0.2769],
        [ 0.0309],
        [ 0.2179],
        [ 0.5443],
        [-0.1941],
        [-0.2115],
        [-0.2507],
        [-0.3291],
        [-0.4886],
        [ 0.2558],
        [ 0.3759],
        [ 0.2139]], dtype=torch.float64, requires_grad=True)

In [26]:
model.bias

tensor([-0.1305], dtype=torch.float64, requires_grad=True)

CALCULATING THE ACCURACY

In [28]:
with torch.no_grad():
  y_pred=model.forward_pass(x_test_tensor.double())
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()}')

Accuracy:0.5236995816230774
